tidder/urls.py
# authly_app/urls.py
from django.urls import path
from django.conf.urls import url
from tidder import views

# SET THE NAMESPACE!
app_name = 'tidder'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    path('register', views.register, name='register'),
    path('user_login', views.user_login, name='user_login'),
    path('newpost', views.create_post, name='create_post'),
    path('post/<int:pk>', views.post_view, name='post_view'),
    path('newcomment', views.create_comment, name='create_comment')
    # path('/api/users', views.sendJson, name='sendJson')
]

tidder_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from tidder import views

urlpatterns=[
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('special', views.special, name='special'),
    path('tidder/', include('tidder.urls')),
    path('logout', views.user_logout, name='logout'),
]

tidder/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

# Create your models here.

        
# class UniqueUser(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     username = models.CharField(max_length=20, default=None)
#     signed_up = models.DateTimeField(auto_now_add=True)
#     is_staff = False

#     def __str__(self):
#         return self.user.username

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    title = models.CharField(max_length=200, blank=True)
    site_url = models.URLField(blank=True) 
    content = models.TextField(blank=True)
    picture = models.ImageField(upload_to='post_pics',blank=True)
    post_time = models.DateTimeField(auto_now_add=True)
    post_vote = models.IntegerField(default=1)

    def __str__(self):
        return self.title

class PostSave(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    save_time = models.DateTimeField(auto_now_add=True)

class CommentPost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_time = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    comment_vote = models.IntegerField(default=1)

    def __str__(self):
        return self.content

class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    # posts = models.ForeignKey(Post, on_delete=models.CASCADE, default=None)
    # comments = models.ForeignKey(CommentPost, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.user.username

class Admin(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    portfolio = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    is_staff=True

    def __str__(self):
        return self.user.username
        

tidder/forms.py
from django import forms
from .models import User, UserProfile, Post, CommentPost

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'password')

class UserProfileForm(forms.ModelForm):

    class Meta():
        model = UserProfile
        fields = ('portfolio_site','profile_pic')

class PostForm(forms.ModelForm):

    class Meta():
        model = Post
        fields = ('title', 'site_url', 'content', 'picture')

class CommentForm(forms.ModelForm):

    class Meta():
        model = CommentPost
        fields = ('post', 'content', 'user')

tidder/views.py
from django.shortcuts import render, redirect
from .forms import UserForm, UserProfileForm, PostForm, CommentForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import User, Post, CommentPost
import datetime

# Create your views here.

def index(request):
    allposts = Post.objects.all()
    return render(request, 'tidder/index.html', {'allposts': allposts})

@login_required
def special(request):
    return HttpResponse("Welcome to tiddeR!")

@login_required
def user_logout(request):
    logout(request)
    return redirect('index')

def register(request):
    registered = False
    # if we are trying to create a user, not get a new user view
    if request.method == 'POST':
        # we are populating a Form object with data from our request body (username, email, password)
        user_form = UserForm(data=request.POST)
        # we are populating a Form object with data from our request body (profile_pic, portfolio_site)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
            return redirect('tidder/login.html')

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request, 'tidder/register.html', {'user_form':user_form,'profile_form':profile_form,'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return redirect('index')
            else:
                return HttpResponse("Your account is inactive")

        else:
            print("Someone tried to login and failed")
            # print(f'They used username: {username} and password: {password}')
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'tidder/login.html', {})

@login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('index')
        else:
            print('\nform is invalid\n')
    else:
        form = PostForm()
    return render(request, 'tidder/post_form.html', {'form': form})

def post_view(request, pk):
    post = Post.objects.get(id=pk)
    return render(request, 'tidder/post_view.html', {'post': post})

@login_required
def create_comment(request):
    if request.method == 'POST':
        cform = CommentForm(request.POST)
        if cform.is_valid():
            comment = cform.save(commit=False)
            comment.user = request.user
            comment.save()
            return redirect('index')
        else:
            print('\nform is invalid\n')
    else:
        cform = CommentForm()
    return render(request, 'tidder/comment_form.html', {'cform': cform})

def comment_view(request, pk):
    comment = CommentPost.objects.get(id=pk)
    return render(request, 'tidder/post_view.html', {'comment': comment})

tidder/templates/tidder/base.html
{% load staticfiles %}


<!DOCTYPE html>
<html>
    <head>
    <meta charset="utf-8">
    <title>Tidder</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
    <body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
        <ul class="nav navbar-nav">
            {# Django Home Link / Admin Link / Register Link #}
            <li><a class="navbar-link" href="{% url 'index' %}">Home</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href="{% url 'tidder:register' %}">Register</a></li> 
            <li><a class="navbar-link" href="{% url 'tidder:create_post' %}">Post</a></li>         
            {# Some logic on what to display for last item#}
            {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
            <li><a class="navbar-link" href="{% url 'tidder:user_login' %}">Login</a></li>
            {% endif %}
        </ul>
        </div>
    </nav>
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
    </body>
</html>

tidder/templates/tidder/comment_form.html
{% extends "tidder/post_view.html" %}
{% load staticfiles %}
{% block content %}
<div>
    <h4>Add a Comment</h4>
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ cform.as_p }}
            <input type="submit" name="" value="Comment">
        </form>
</div>
{% endblock %}

tidder/templates/tidder/index.html
{% extends "tidder/base.html" %}
{% load staticfiles %}

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>Welcome to tiddeR !</h1>
        <h2>The backpage of the internet</h2>
    {% if user.is_authenticated %}
        <h3>Hello {{ user.username }}</h3>
    {% else %}
        <h3>Register or Login if you'd like to</h3>
    {% endif %}
    </div>
</div>

    <div class="posts">
    {% for post in allposts %}
    <p>{{ post.post_vote }} {{ post.picture }}<h4><a href="">{{ post.title }}</a></h4> <a href="{{ post.site_url }}">{{ post.site_url }}</a> {{ post.post_time }}</p>
    <h4>{{ post.user }}</h4>
    <p>{{ post.content }}</p>

    <hr>
    {% endfor %}
    </div>
{% endblock %}

tidder/templates/tidder/login.html
{% extends 'tidder/base.html' %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>Login here :</h1>
        <form method="post" action="{% url 'tidder:user_login' %}">
        {% csrf_token %}
        {# A more "HTML" way of creating the login form#}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Username">
            <label for="password">Password:</label>
            <input type="password" name="password" placeholder="Password">
            <input type="submit" name="" value="Login">
        </form>
    </div>
</div>
{% endblock %}

tidder/templates/tidder/post_form.html
{% extends "tidder/base.html" %}
{% load staticfiles %}
{% block content %}
<div class="container">
    <div class="jumbotron">
    
        <h1>Create a Post</h1>
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" name="" value="Post">
        </form>
        
    </div>
</div>
{% endblock %}

tidder/templates/tidder/post_view.html
{% extends "tidder/base.html" %}
{% load staticfiles %}


{% block content %}
<div>
    <h4><a href="{{ post.site_url }}">{{ post.site_url }}</a></h4>
    <h3>Title: {{ post.title }}</h3>
    <h4>Content: {{ post.content }}</h4>
</div>
<hr>
<div>
    <h4>Add a Comment:</h4>
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ cform.as_p }}
                <input type="submit" name="" value="Comment">
        </form>
                
</div>

{% endblock %}

tidder/templates/tidder/register.html
{% extends "tidder/base.html" %}
{% load staticfiles %}
{% block content %}
<div class="container">
    <div class="jumbotron">
    {% if registered %}

        <h1>Thank you for registering!</h1>
    
    {% else %}
    
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Register">
        </form>
        
    {% endif %}
    </div>
</div>
{% endblock %}